-- Add default skills to HireFlow database
INSERT INTO skills (name) VALUES
('JavaScript'),
('Python'),
('Java'),
('React'),
('Node.js'),
('SQL'),
('MongoDB'),
('Git'),
('Docker'),
('AWS'),
('Communication'),
('Leadership'),
('Problem Solving'),
('Team Work'),
('Project Management'),
('Agile'),
('HTML/CSS'),
('TypeScript'),
('Angular'),
('Vue.js'),
('C++'),
('C#'),
('PHP'),
('Ruby'),
('Spring Boot'),
('Django'),
('Flask'),
('PostgreSQL'),
('Redis'),
('Kubernetes'),
('CI/CD'),
('Azure'),
('Google Cloud'),
('REST API'),
('GraphQL'),
('Machine Learning'),
('Data Analysis'),
('Tableau'),
('Power BI'),
('Excel')
ON DUPLICATE KEY UPDATE name=name;
